### ISSUE TITLE
Real time website themeing

### ISSUE THREAD

**Issue by Allcharles** [QutEcoacoustics/workbench-client#1184]
It would be nice to have the ability to change the theme of the website in real time. This will allow us to make the theme of the website something which can changed in the environment, changed on the server, or even changed depending on user preferences.
Currently bootstrap 4 and 5 do not support the use of CSS variables to change colours in real time, instead relying on SASS' compile time variables. Thus to implement things in a usable manner until this feature is implemented, we need to override the themes for specific components as required. An example for the primary theme button can be seen below:

```scss
@import "~bootstrap/scss/variables";
@import "~bootstrap/scss/buttons";

:root {
  --baw-primary-red: 255;
  --baw-primary-green: 255;
  --baw-primary-blue: 255;
    
  --baw-primary: rgb(
    --baw-primary-red,
    --baw-primary-green,
    --baw-primary-blue
  );
  --baw-primary-inverse: calc(
    (
      (
        (
          (var(--baw-primary-red) * 299) +
          (var(--baw-primary-green) * 587) +
          (var(--baw-primary-blue) * 114)
        ) / 1000
      ) - 128
    ) * -1000
  );
  
  --baw-primary-border: rgb(255, 255, 255);
  --baw-primary-lighter: rgb(255, 255, 255);
  --baw-primary-lightest: rgb(255, 255, 255);
  --baw-primary-darker: rgb(255, 255, 255);
  --baw-primary-darkest: rgb(255, 255, 255);
}

.btn-primary {
  @extend .btn-primary;
  background-color: var(--bs-primary, $primary);
}
```

The red, green, and blue for each theme (primary, secondary, info, etc) will be inserted by an angular service. This update should also be included with upgrading to bootstrap 5, and using the beta build of ngx-bootstrap.
